version: '2'
services:
  gssgn:
    image: gssgn
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://gssgn-postgresql:5432/gssgn'
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  gssgn-postgresql:
    image: 'postgres:14'
    environment:
      - POSTGRES_USER=itsol
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
